### ISSUE TITLE
AD: default to a safer example domain

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-container#39]
Because I originally cooked up the scripts we use for the AD image as a quick and dirty prototype for my own use the scripts set up the samba AD server with a phony subdomain of a domain I currently have registered for my own personal use.
While it's good that I know that there will not be any conflicts we should probably start looking towards cleaning this up sooner, rather than later, and preventing something so linked to me from proliferating in the scripts and tests.

I did a quick search and found https://tools.ietf.org/html/rfc6761
Based on this I think we're best off defaulting to "<something>.test." as our domain for local, ephemeral, test domains. At the same time I can make either the whole string or the "<something>" bit based on an environment variable to start making the scripts more usable for other cases and reducing the amount of stuff that is hard coded.

Opinions, @obnoxxx ?

**Comment by obnoxxx** [comment]
Yes, this is right.
How about `testdom.sink.test` ? ==> PR #40
