### ISSUE TITLE
Metrics - implement a samba metrics collector and exporter that is compatible with Prometheus

### ISSUE THREAD

**Issue by raghavendra-talur** [samba-in-kubernetes/samba-container#41]
The samba container should have a way to export the metrics. This will make it more cloud native solution.

Are there any other options that parsing smbstatus?

Notes:

- Samba should be compiled with profiling enabled (--with-profiling-data)

**Comment by raghavendra-talur** [comment]
For CTDB specifically, there is no client library that lives outside the main samba code. The readily available option is to scrape the output of ctdb command line.

See https://www.spinics.net/lists/samba/msg166658.html

**Comment by raghavendra-talur** [comment]
After having looked at the options, we think it would be better to have samba and ctdb export their metrics in form that is easy to parse; something like json. The work required to make that happen is tracked in

The scope of this issue is now reduced to implementing a metrics collector and exporter that collects the metrics from samba and ctdb and publishes it in a form that can be consumed by prometheus.

**Comment by anoopcs9** [comment]
This is done and is available with https://github.com/samba-in-kubernetes/smbmetrics
