### ISSUE TITLE
Using samba's ntacl support requires CAP_SYS_ADMIN

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-container#42]
Currently samba wants to write ALCs into `security.NTACL` which requires the admin capablity - aka a privileged container.

An effort to make this configurable in samba is located here:
https://gitlab.com/samba-team/samba/-/merge_requests/1908

PS. I thought I had tracked this already but I either tracked it somewhere else and forgot where or simply forgot previously. Don't be too shocked if you find a dupe of this :-)

**Comment by anoopcs9** [comment]
Closing in favour of https://github.com/samba-in-kubernetes/sambacc/issues/10.
