### ISSUE TITLE
Configurable Samba AD container.

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-container#62]
We have our Samba AD DC container (used for testing) but it has a largely hard-coded configuration. We should make (parts of) this changeable so that at least we can vary parameters during testing.

**Comment by phlogistonjohn** [comment]
This issue requires changes in samba-in-kubernetes/sambacc#28 and we have a draft in #58 but I can safely say this work is in progress now.

**Comment by phlogistonjohn** [comment]
The changes in #58 have been merged. To complete this task we should add some simple tests to validate the configuration can in fact be changed.

**Comment by anoopcs9** [comment]
@phlogistonjohn Should we wait for https://github.com/samba-in-kubernetes/sambacc/pull/45 before closing the issue?

**Comment by phlogistonjohn** [comment]
No, the core features that I was thinking of when I wrote the issue were things like the realm, node name, users, and groups - these were all hard coded in the old shell script approach. Issue samba-in-kubernetes/sambacc#43 is about getting a more generic set of global options into the smb.conf, but the containers are configurable now. I think its best to track that separately,  especially since there's an issue for it.
