### ISSUE TITLE
Switch to `centos:stream9` base image

### ISSUE THREAD

**Issue by anoopcs9** [samba-in-kubernetes/samba-container#78]
Use `quay.io/centos/centos:stream9` as the base image for building Samba server and AD server images.

**Comment by anoopcs9** [comment]
`python-inotify_simple` is now [available](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-c3b6e6b1f3) with EPEL 9 and an attempt to build sambacc was [successful](https://github.com/samba-in-kubernetes/sambacc/commit/1eff2a4c9e4a0a262cc7a35a54133aa20d58274e). But then while trying to build from samba-container repository I realized that we miss `samba-dc` altogether from RHEL 😕 . Still plain server images can be [built](https://github.com/anoopcs9/samba-container/commit/35428c6854da58a90b3780c92a45ed58bc6e710d).

**Comment by ibotty** [comment]
Any news?

**Comment by obnoxxx** [comment]
do we still want this, or rather close it, @phlogistonjohn , @anoopcs9 ?

**Comment by anoopcs9** [comment]
> do we still want this, or rather close it, @phlogistonjohn , @anoopcs9 ?

This is an issue and can probably stay open.

**Comment by anoopcs9** [comment]
_Update_:

Server images can be built with CentOS base.
AD Server images(with Samba packages from nightly RPM repository) can be built with CentOS base.

**Comment by obnoxxx** [comment]
@ibotty  wrote: 

> Any news?


As @anoopcs9  has mentioned in the previous comment, I think this has long been done:

* ad-server: #142 
* server: #98 

closing this issue as completed.
