### ISSUE TITLE
github actions generates many warnings

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/samba-container#80]
I figure this is because some of the actions were hare configured and are "out of date".

Example (15 warnings):
https://github.com/samba-in-kubernetes/samba-container/actions/runs/3391037070

They seem to boil down to:
* `Node.js 12 actions are deprecated.`
* `The `set-output` command is deprecated and will be disabled soon `

The latter may be more of a priority for the "... will be disabled soon" bit. Of course, they don't say how soon.

Anyone want to update the github actions?  It may also be worth checking on the up-to-date-ness of the actions in some of the other sink repos too.

**Comment by synarete** [comment]
@phlogistonjohn See: https://github.com/samba-in-kubernetes/samba-container/pull/81

**Comment by anoopcs9** [comment]
> The latter may be more of a priority for the "... will be disabled soon" bit. Of course, they don't say how soon.

Blog [link ](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)provided along with the deprecation warning says the following:
> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

**Comment by phlogistonjohn** [comment]
Both issues were resolved.
